name: main-action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # 1. 최신 태그 정보 가져오기
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_latest_tag.outputs.latest_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

  # 2. Black Duck 스캔 실행
  blackduck-scan:
    needs: [get_tag] # 태그 정보를 받아온 후 실행
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # uv 환경에서 블랙덕이 정확하게 스캔할 수 있도록 uv 설정 추가
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies with uv
        run: uv sync # 블랙덕 Detect가 의존성 구조를 파악할 수 있게 환경 동기화

      - name: Run Black Duck Scan
        id: black-duck-sca-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        env:
          # 환경 변수와 arguments를 함께 사용하여 프로젝트 이름 지정
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          detect_search_depth: 10
          blackducksca_scan_full: true
          detect_args: |
            --detect.project.name=${{ github.event.repository.name }}
            --detect.project.version.name=${{ needs.get_tag.outputs.latest_tag }}
            --detect.excluded.detector.types=GIT
            --blackduck.trust.cert=true
            --detect.risk.report.pdf=true
            --detect.accuracy.required=NONE
            --detect.project.group.name=IS
            --detect.pip.path=uv
            --detect.python.path=uv
            --detect.pip.requirements.path=pyproject.toml
